import assert from 'node:assert/strict'
import { readFile } from 'node:fs/promises'

const source = await readFile(new URL('./TeacherClassManage.jsx', import.meta.url), 'utf8')
const cssSource = await readFile(new URL('../index.css', import.meta.url), 'utf8')

assert.match(source, /workspace-page/)
assert.match(source, /WorkspacePageHeader/)
assert.match(source, /WorkspaceMetricCard/)
assert.match(source, /WorkspaceSectionCard/)
assert.match(source, /teacher-manage-focus-grid/)
assert.match(source, /TeamOutlined/)
assert.match(source, /ApartmentOutlined/)
assert.match(source, /ReadOutlined/)
assert.match(source, /AlertOutlined/)
assert.ok(source.includes('教师管理工作台'), 'Teacher manage should include workspace title copy')
assert.ok(source.includes('教师总数'), 'Teacher manage should include teacher total metric copy')
assert.ok(source.includes('已绑定班级'), 'Teacher manage should include bound classes metric copy')
assert.ok(source.includes('已分配科目组'), 'Teacher manage should include assignment group metric copy')
assert.ok(source.includes('待补齐项'), 'Teacher manage should include pending metric copy')
assert.ok(source.includes('主流程工作区'), 'Teacher manage should include primary workflow copy')
assert.ok(source.includes('选择教师'), 'Teacher manage should include teacher picker copy')
assert.ok(source.includes('绑定班级'), 'Teacher manage should include class binding copy')
assert.ok(source.includes('分配科目'), 'Teacher manage should include subject assignment copy')
assert.ok(source.includes('当前教师概览'), 'Teacher manage should include current teacher overview copy')
assert.ok(source.includes('待处理提醒'), 'Teacher manage should include pending reminder copy')
assert.ok(source.includes('矩阵总览'), 'Teacher manage should include matrix overview copy')
assert.ok(source.includes('班级-科目-教师矩阵'), 'Teacher manage should include matrix copy')
assert.ok(source.includes('分配汇总'), 'Teacher manage should include summary copy')
assert.ok(source.includes('按教师-科目聚合'), 'Teacher manage should include grouped summary copy')
assert.match(cssSource, /\.teacher-manage-focus-grid/)
assert.match(cssSource, /\.teacher-manage-side-stack/)

const headerIndex = source.indexOf('教师总数')
const workflowIndex = source.indexOf('主流程工作区')
const matrixIndex = source.indexOf('班级-科目-教师矩阵')
const summaryIndex = source.indexOf('分配汇总')
const teacherSelectIndex = source.indexOf('value={selectedTeacher}')
const bindClassIndex = source.indexOf('value={bindClassIds}')
const selectedClassIndex = source.indexOf('value={selectedClassIds}')
const subjectIndex = source.indexOf('value={selectedSubject}')
assert.ok(headerIndex > -1 && matrixIndex > -1 && headerIndex < matrixIndex, 'Teacher manage should render metrics before matrix section')
assert.ok(workflowIndex > -1 && matrixIndex > -1 && workflowIndex < matrixIndex, 'Teacher manage should render workflow before matrix section')
assert.ok(matrixIndex > -1 && summaryIndex > -1 && matrixIndex < summaryIndex, 'Teacher manage should render matrix before summary section')
assert.ok(teacherSelectIndex > -1 && bindClassIndex > -1 && teacherSelectIndex < bindClassIndex, 'Teacher manage should place bind-class picker after teacher picker')
assert.ok(selectedClassIndex > -1 && subjectIndex > -1 && selectedClassIndex < subjectIndex, 'Teacher manage should place selected-class picker before subject picker')

console.log('teacher manage workspace content checks passed')
